---
task_1:
  description: | 
    Identify the most important point in the news about {topic}.
    Focus on identifying pros and cons and the overall narrative.
    Your final report should clearly articulate the key points and arenas of opportunities, and potential risks.
  expected_output: |
    A summary of the top 5 news articles found within the date range.
    Make sure to save the file.
  verbose: True

task_2:
  description: | 
    Compose an insightful article on {topic}.
    Focus on the key points, write a summary, including any social, cultural, political and econimic and implications.
    Preserve all source link, including URLs.
    This article should be easy to understand, engaging, and positive.
  expected_output: |
    A summary of the top 5 news articles found within the date range.
    Make sure to save the file.
    Your final report will be in Markdown format and will include a title, date range, and a list of key points with link to sources in the following format:

    # title
    ###### {start_date} - {end_date}

      - ### key_point
        summary
        - links
      - ### key_point
        summary
        - links
 
  verbose: True  
