---
task_1:
  description: | 
    Search for news articles related to {topic} between {start_date} and {end_date}.
    Focus on finding articles from reputable sources and summarize the key points.
    Summarize the key points from each article.
  expected_output: |
    A summary of the top 5 news articles found within the date range.
    Make sure to save the file.
    Your final report will be in Markdown format and will include a title, date range, and a list of key points with link to sources in the following format:

    # title
    ###### {start_date} - {end_date}

      - ### key_point
        summary
        - links
      - ### key_point
        summary
        - links
 
  verbose: True
  
